---

- name: Install Squid
  yum: name={{ item }} state=present 
  with_items:
  - python-passlib
  - squid

- name: Add Squid Users
  htpasswd: path=/etc/squid/passwdfile name={{ item.user }} password={{ item.passwd }} owner=root group=root mode=0640
  with_items: "{{ squid_users }}"

- name: Configure Squid
  template: src=squid.conf.j2 dest=/etc/squid/squid.conf owner=root group=root mode=0640

- name: Start Squid
  service: name=squid state=running enabled=yes

...
